#!/usr/bin/env bash

javac -classpath external_libs/json-simple-1.1.1.jar \
      Pinger.java \
      PingsClient.java \
      PingsApplet.java \
      TestPingers.java \
      ClientInfo.java \
      ServerProxy.java \
      Launcher.java \
      IcmpPinger.java \
      TcpPinger.java \
      TraceRouter.java
