#!/usr/bin/env bash

mkdir -p doc

javadoc \
    -private \
    -d doc \
    ServerProxy.java \
    ClientInfo.java \
    Launcher.java \
    IcmpPinger.java \
    TcpPinger.java \
    TraceRouter.java
